version: 3.8
services:

  neo-smb:
    image: docker.io/dockurr/samba:latest
    environment:
      NAME: "data"
      USER: "smb"
      PASS: "smb"
      UID: 1000
      GID: 1000
    ports:
      - 445:445
    networks:
      - netapp-neo
    volumes:
      - neo-smb:/storage
    restart: unless-stopped

  netapp-neo:
    image: ghcr.io/netapp/netapp-copilot-connector:3.2.4
    user: "1000:1000"
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
      - DAC_OVERRIDE
    security_opt:
      - apparmor:unconfined
    ports:
      - "8081:8080"
    networks:
      - netapp-neo
    env_file:
      - .env
    environment:
      - PORT=8080
    volumes:
      - neo-226:/app/data
    restart: unless-stopped

  netapp-neo-ui:
    image: ghcr.io/netapp/neo-ui-framework:3.2.2
    ports:
      - "8080:80"
    environment:
      - NEO_API=http://netapp-neo:8080   # ← add this
    networks:
      - netapp-neo
    restart: unless-stopped

volumes:
  neo-smb:
    driver: local
  neo-226:
    driver: local

networks:
  netapp-neo:
    driver: bridge